// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPP5bCR2PJfookF4-Y7fidvrvF9eMvlKA',
    appId: '1:437138601706:web:2ccd679be7eefd7e504993',
    messagingSenderId: '437138601706',
    projectId: 'qrtest-70204',
    authDomain: 'qrtest-70204.firebaseapp.com',
    storageBucket: 'qrtest-70204.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAyUzdlFGEQUTpZco_IwS-_TlqyDs_aFw',
    appId: '1:437138601706:android:f4991d8eb939e073504993',
    messagingSenderId: '437138601706',
    projectId: 'qrtest-70204',
    storageBucket: 'qrtest-70204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzpVyUSlU1VuS3pOqdF1AOSwZti17bSs8',
    appId: '1:437138601706:ios:7471dfe4923c87f0504993',
    messagingSenderId: '437138601706',
    projectId: 'qrtest-70204',
    storageBucket: 'qrtest-70204.appspot.com',
    iosBundleId: 'com.example.qrCodeScannerGeneretor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzpVyUSlU1VuS3pOqdF1AOSwZti17bSs8',
    appId: '1:437138601706:ios:61509ab455fb9bd8504993',
    messagingSenderId: '437138601706',
    projectId: 'qrtest-70204',
    storageBucket: 'qrtest-70204.appspot.com',
    iosBundleId: 'com.example.qrCodeScannerGeneretor.RunnerTests',
  );
}
